- name: Install packages
  become: yes
  package: "name={{ item }} state=present"
  with_items:
    - postgresql
    - postgresql-contrib

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "{{ pg_hba_path }}"
  register: postgres_data

- name: Debug
  debug: "{{ postgres_data }}"

# - name: "Initialize PostgreSQL"
#   shell: "postgresql-setup initdb"
#   when: not postgres_data.stat.exists

# - name: "Start and enable services"
#   become: yes
#   service: "name={{ item }} state=started enabled=yes"
#   with_items:
#     - postgresql
