---

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: macos.yml
  when: ansible_os_family == 'Darwin'

- name: Install Oh-my-zsh
  become_user: adrian
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: '~/.oh-my-zsh'
    depth: 1

- name: Install powerlevel10k
  become_user: adrian
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: '~/.oh-my-zsh/custom/themes/powerlevel10k'
    depth: 1
