---

- block:
  - name: Install ZSH
    become: yes
    package: name=zsh state=present
    when: ansible_os_family == 'Debian'

- block:
  - name: Install ZSH
    become: no
    package: name=zsh state=present
    when: ansible_os_family == 'Darwin'

- block:
  - name: Setup zsh as default shell
    become: yes
    user: 
      name: adrian
      shell: /usr/bin/zsh
    when: ansible_os_family == 'Debian'
  - name: Setup zsh as default shell
    become: yes
    user: 
      name: adrian
      shell: /bin/zsh
    when: ansible_os_family == 'Darwin'

- block:
  - name: Install Oh-my-zsh
    become_user: adrian
    git:
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: '~/.oh-my-zsh'
      depth: 1

- block:
  - name: Install powerlevel10k
    become_user: adrian
    git:
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: '~/.oh-my-zsh/custom/themes/powerlevel10k'
      depth: 1
