- name: Start Postgres
  become: yes
  service: name=postgresql state=started  
  when: ansible_os_family == 'Debian'
  listen: "start postgres"

- name:  Restart Postgres
  become: yes
  service: name=postgresql state=restarted  
  when: ansible_os_family == 'Debian'
  listen: "restart postgres"

