---

- name: Add neovim ppa 
  become: true
  apt_repository: repo="{{ neovim_ppa }}" state=present

- name: Install neovim from ppa
  become: true
  apt: name="{{ neovim_name }}" state="{{ install_state }}"

- name: Install python neovim plugin
  pip: 
    name: neovim 
    executable: "{{ pip3_name }}"
    state: "{{ install_state }}"
    extra_args: --user

- name: Make "{{ neovim_config_dir }}/autoload" directory
  file: path="{{ neovim_config_dir }}/autoload" state=directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ neovim_config_dir }}/autoload/plug.vim"
    force: yes
