---

# Install neovim
- block: 
    - name: Add neovim ppa 
      apt_repository: repo="{{ neovim_ppa }}" state=present
      when: ansible_os_family == "Debian"

    - name: Install neovim from ppa
      apt: name="{{ neovim_name }}" state="{{ install_state }}"
  become: true
  become_user: root
  tags:
    - bootstrap
    - install
    - update
  when: ansible_os_family == 'Debian'

- block:
    - name: Install python neovim plugin
      pip: 
        name: neovim 
        executable: "{{ pip3_name }}"
        state: "{{ install_state }}"
        extra_args: --user
  when: ansible_os_family == 'Debian'

# Install vim-plug
- block:
    - name: Make "{{ neovim_config_dir }}/autoload" directory
      file: path="{{ neovim_config_dir }}/autoload" state=directory

    - name: Install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ neovim_config_dir }}/autoload/plug.vim"
        force: yes
  tags:
    - bootstrap
    - configure

- block:
    - name: Install vim plugins 
      command: nvim "+silent! PlugInstall!" +qall!
      tags: plugins
  tags:
    - bootstrap
    - configure
    - update
