- name: Debian - Install APT packages
  become: yes
  package:
    name:
      - build-essential
      - git
      - wget
      - tmux
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev 
      - libxcb-xfixes0-dev 
      - libxkbcommon-dev
      - ripgrep
      - software-properties-common
      - python3-dev
      - python3-pip
      - i3
      - curl
      - libtool
      - libtool-bin
      - postgresql-client
      - libpq5
      - libpq-dev
    state: present

- name: Debian - Install Snap packages
  become: yes
  snap:
    name:
      - emacs
    classic: true
    state: present
