- name: Debian - Install packages
  become: yes
  package:
    name:
      - build-essential
      - git
      - wget
      - tmux
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev 
      - libxcb-xfixes0-dev 
      - libxkbcommon-dev
      - ripgrep
      - software-properties-common
      - python3-dev
      - python3-pip
      - emacs
      - i3
    state: present
