- name: Darwin - Install packages
  homebrew:
    name:
      - git
      - wget
      - tmux
      - cmake
      - pkg-config
      - ripgrep
      - gnu-tar
      - fzf
    state: present
- name: Darwin - Install Alacritty
  homebrew_cask:
    name:
      - alacritty
      - emacs
    state: present
