- name: Darwin - Install packages
  homebrew:
    name:
      - git
      - wget
      - tmux
      - cmake
      - pkg-config
      - ripgrep
      - gnu-tar
      - fzf
      - coreutils
      - fd
    state: present

- name: Darwin - Install Alacritty
  homebrew_cask:
    name:
      - alacritty
    state: present

- name: Darwin - Tap Emacs cask
  homebrew_tap:
    name: 'railwaycat/emacsmacport'

- name: Darwin - Install emacs
  homebrew:
    name: emacs-mac
    install_options: with-modules

- name: Darwin - Symlink Emacs.app
  file:
    src: /usr/local/opt/emacs-mac/Emacs.app
    dest: /Applications/Emacs.app
    state: link
