- block:
  - name: Debian - Install packages
    become: yes
    package:
      name:
        - build-essential
        - git
        - wget
        - tmux
        - cmake
        - pkg-config
        - libfreetype6-dev
        - libfontconfig1-dev 
        - libxcb-xfixes0-dev 
        - libxkbcommon-dev
        - ripgrep
        - software-properties-common
        - python-pip
        - python3-dev
        - python3-pip
        - i3
      state: present
    when: ansible_os_family == 'Debian'
  - name: Darwin - Install packages
    package:
      name:
        - git
        - wget
        - tmux
        - cmake
        - pkg-config
        - ripgrep
        - gnu-tar
        - neovim
      state: present
  - name: Darwin - Install Alacritty
    homebrew_cask:
      name:
        - alacritty
      state: present
    when: ansible_os_family == 'Darwin'
