#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

if [ "$(uname -s)" = "Linux" ]
then
  sudo apt-get install build-essential
fi


cd "$(dirname $0)"/..
sh -c "${system/install.sh}"
# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
