---
fonts_dir_debian: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
fonts_dir_darwin: /Library/Fonts
fonts_dir: "{{ lookup('vars', 'fonts_dir_'+ansible_os_family|lower, default=fonts_dir_debian) }}"
