---

- block:
  - name: Install pyenv
    become_user: adrian
    git:
      repo: https://github.com/pyenv/pyenv.git
      dest: '~/.pyenv'
      depth: 1

- block:
  - name: Install pyenv-virtualenv
    become_user: adrian
    git:
      repo: https://github.com/pyenv/pyenv-virtualenv.git
      dest: '~/.pyenv/plugins/pyenv-virtualenv'
      depth: 1

